version: 2.1
orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  test:
    docker:
      - image: circleci/node:12
        environment:
          NODE_ENV: development
    steps:
      - checkout
      - run: yarn flow
      - run: yarn lint
      - run: yarn test:unit --maxWorkers=2
      - run:
          command: yarn cosmos
          background: true
      - run: yarn test:visual --maxWorkers=2
workflows:
  flatris:
    jobs:
      - test
